# Generated by Django 4.0.5 on 2022-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humphreysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busline',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
